version: '3.9'
services: 
    db:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        environment: 
            MYSQL_DATABASE: ${AUTH_SERVICE_DB}
            MYSQL_USER: ${AUTH_USER}
            MYSQL_PASSWORD: ${AUTH_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080